<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Daily Sales Report</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 11px; color: #1f2937; }
        .header { border-bottom: 2px solid #2563eb; padding-bottom: 10px; margin-bottom: 14px; }
        .title { font-size: 18px; font-weight: bold; margin-bottom: 4px; }
        .muted { color: #6b7280; }
        .section {
            margin-top: 14px;
            page-break-inside: avoid;
            break-inside: avoid-page;
        }
        .section h3 {
            font-size: 13px;
            margin: 0 0 8px;
            color: #111827;
            page-break-after: avoid;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            page-break-inside: avoid;
            break-inside: avoid-page;
        }
        thead { display: table-header-group; }
        tfoot { display: table-row-group; }
        tr {
            page-break-inside: avoid;
            break-inside: avoid;
        }
        th, td { border: 1px solid #e5e7eb; padding: 6px; vertical-align: top; }
        th { background: #f3f4f6; text-align: left; }
        .text-right { text-align: right; }
    </style>
</head>
<body>
    <div class="header">
        <div class="title">Daily Sales Report</div>
        <div class="muted">Date: {{ $selectedDate->format('F d, Y') }}</div>
        <div class="muted">Generated by: {{ $generatedBy }} | {{ $generatedAt->format('F d, Y h:i A') }}</div>

        @if($sections['includeHeader'])
            <div style="margin-top: 8px;">
                <strong>Company:</strong> {{ $shop->name ?? 'N/A' }}<br>
                <strong>Email:</strong> {{ $shop->email ?? 'N/A' }}<br>
                <strong>Address:</strong> {{ $shop->address ?? 'N/A' }}<br>
                <strong>Phone:</strong> {{ $shop->phone ?? 'N/A' }}
            </div>
        @endif
    </div>

    @if($sections['includeSummary'] && $salesData)
        <div class="section">
            <h3>Sales Summary</h3>
            <table>
                <tr><th>Total Sales</th><td class="text-right">LKR {{ number_format($salesData['total_sales']) }}</td></tr>
                <tr><th>Total Orders</th><td class="text-right">{{ $salesData['total_orders'] }}</td></tr>
                <tr><th>Total Items Sold</th><td class="text-right">{{ $salesData['total_items_sold'] }}</td></tr>
                <tr><th>Gross Profit</th><td class="text-right">LKR {{ number_format($salesData['gross_profit']) }}</td></tr>
            </table>
        </div>
    @endif

    <div class="section">
        <h3>Sales</h3>
        @php $salesTableTotal = $salesOrdersData->sum('total'); @endphp
        <table>
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Invoice No</th>
                    <th>Customer Name</th>
                    <th>Payment Type</th>
                    <th>Status</th>
                    <th class="text-right">Total Cost</th>
                </tr>
            </thead>
            <tbody>
                @forelse($salesOrdersData as $sale)
                    @php
                        $paymentType = strtolower((string) ($sale->payment_type ?? ''));
                        $isCredit = in_array($paymentType, ['credit', 'due'], true);
                        $status = $isCredit
                            ? (($sale->due ?? 0) > 0 ? 'Due' : 'Completed')
                            : 'Completed';
                    @endphp
                    <tr>
                        <td>{{ $sale->order_date ? $sale->order_date->format('Y-m-d') : '-' }}</td>
                        <td>{{ $sale->invoice_no ?? '-' }}</td>
                        <td>{{ $sale->customer?->name ?? 'Walk-in Customer' }}</td>
                        <td>{{ ucfirst(str_replace('_', ' ', $sale->payment_type ?? '-')) }}</td>
                        <td>{{ $status }}</td>
                        <td class="text-right">LKR {{ number_format($sale->total ?? 0, 2) }}</td>
                    </tr>
                @empty
                    <tr><td colspan="6">No sales available.</td></tr>
                @endforelse
                @if($salesOrdersData->isNotEmpty())
                    <tr>
                        <th colspan="5">Total Sales Value</th>
                        <th class="text-right">LKR {{ number_format($salesTableTotal, 2) }}</th>
                    </tr>
                @endif
            </tbody>
        </table>
    </div>

    @if($sections['includePayments'])
        <div class="section">
            <h3>Payment Methods</h3>
            @php $paymentMethodsTotal = $paymentMethodData->sum('total_amount'); @endphp
            <table>
                <thead>
                    <tr>
                        <th>Method</th>
                        <th class="text-right">Orders</th>
                        <th class="text-right">Amount</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse($paymentMethodData as $method => $data)
                        <tr>
                            <td>{{ ucfirst(str_replace('_', ' ', $method)) }}</td>
                            <td class="text-right">{{ $data->count }}</td>
                            <td class="text-right">LKR {{ number_format($data->total_amount) }}</td>
                        </tr>
                    @empty
                        <tr><td colspan="3">No payment data available.</td></tr>
                    @endforelse
                    @if($paymentMethodData->isNotEmpty())
                        <tr>
                            <th colspan="2">Total Payment Value</th>
                            <th class="text-right">LKR {{ number_format($paymentMethodsTotal, 2) }}</th>
                        </tr>
                    @endif
                </tbody>
            </table>
        </div>
    @endif

    @if($sections['includeExpenses'])
        <div class="section">
            <h3>Expenses</h3>
            @php $expenseRows = $expensesData->flatMap(fn($items) => $items); @endphp
            @php $expensesTotal = $expenseRows->sum('amount'); @endphp
            <table>
                <thead>
                    <tr>
                        <th>Type</th>
                        <th>Description</th>
                        <th class="text-right">Amount</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse($expenseRows as $expense)
                        <tr>
                            <td>{{ ucfirst(str_replace('_', ' ', $expense->type ?? '')) }}</td>
                            <td>{{ $expense->notes ?? '-' }}</td>
                            <td class="text-right">LKR {{ number_format($expense->amount ?? 0, 2) }}</td>
                        </tr>
                    @empty
                        <tr><td colspan="3">No expenses available.</td></tr>
                    @endforelse
                    @if($expenseRows->isNotEmpty())
                        <tr>
                            <th colspan="2">Total Expenses</th>
                            <th class="text-right">LKR {{ number_format($expensesTotal, 2) }}</th>
                        </tr>
                    @endif
                </tbody>
            </table>
        </div>
    @endif

    @if($sections['includePurchases'])
        <div class="section">
            <h3>Purchases</h3>
            @php $purchasesTotal = $purchasesData->sum('total_amount'); @endphp
            <table>
                <thead>
                    <tr>
                        <th>Vendor</th>
                        <th>Category</th>
                        <th>Status</th>
                        <th class="text-right">Amount</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse($purchasesData as $purchase)
                        <tr>
                            <td>{{ $purchase->vendor_name ?? 'N/A' }}</td>
                            <td>{{ $purchase->category ?? '-' }}</td>
                            <td>{{ ucfirst($purchase->status ?? '-') }}</td>
                            <td class="text-right">LKR {{ number_format($purchase->total_amount ?? 0, 2) }}</td>
                        </tr>
                    @empty
                        <tr><td colspan="4">No purchases available.</td></tr>
                    @endforelse
                    @if($purchasesData->isNotEmpty())
                        <tr>
                            <th colspan="3">Total Purchases Value</th>
                            <th class="text-right">LKR {{ number_format($purchasesTotal, 2) }}</th>
                        </tr>
                    @endif
                </tbody>
            </table>
        </div>
    @endif

    @if($sections['includeTransactions'])
        <div class="section">
            <h3>Transactions</h3>
            @php $transactionsTotal = $transactionsData->sum('total_amount'); @endphp
            <table>
                <thead>
                    <tr>
                        <th>Type</th>
                        <th>Vendor</th>
                        <th>Status</th>
                        <th class="text-right">Amount</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse($transactionsData as $transaction)
                        <tr>
                            <td>{{ ucfirst(str_replace('_', ' ', $transaction->transaction_type ?? '-')) }}</td>
                            <td>{{ $transaction->vendor_name ?? 'N/A' }}</td>
                            <td>{{ ucfirst($transaction->status ?? '-') }}</td>
                            <td class="text-right">LKR {{ number_format($transaction->total_amount ?? 0, 2) }}</td>
                        </tr>
                    @empty
                        <tr><td colspan="4">No transactions available.</td></tr>
                    @endforelse
                    @if($transactionsData->isNotEmpty())
                        <tr>
                            <th colspan="3">Total Transactions Value</th>
                            <th class="text-right">LKR {{ number_format($transactionsTotal, 2) }}</th>
                        </tr>
                    @endif
                </tbody>
            </table>
        </div>
    @endif

    @if($sections['includeDeliveries'])
        <div class="section">
            <h3>Deliveries</h3>
            @php $deliveriesTotal = $deliveriesData->sum('cost'); @endphp
            <table>
                <thead>
                    <tr>
                        <th>Tracking #</th>
                        <th>From</th>
                        <th>To</th>
                        <th class="text-right">Cost</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse($deliveriesData as $delivery)
                        <tr>
                            <td>{{ $delivery->tracking_number ?? 'N/A' }}</td>
                            <td>{{ $delivery->from_location ?? '-' }}</td>
                            <td>{{ $delivery->to_location ?? '-' }}</td>
                            <td class="text-right">LKR {{ number_format($delivery->cost ?? 0, 2) }}</td>
                        </tr>
                    @empty
                        <tr><td colspan="4">No deliveries available.</td></tr>
                    @endforelse
                    @if($deliveriesData->isNotEmpty())
                        <tr>
                            <th colspan="3">Total Delivery Cost</th>
                            <th class="text-right">LKR {{ number_format($deliveriesTotal, 2) }}</th>
                        </tr>
                    @endif
                </tbody>
            </table>
        </div>
    @endif

    @if($sections['includeActivities'])
        <div class="section">
            <h3>Activity Log</h3>
            @php $activitiesTotal = $activitiesData->count(); @endphp
            <table>
                <thead>
                    <tr>
                        <th>Action</th>
                        <th>Model</th>
                        <th>User</th>
                        <th>Description</th>
                        <th>Time</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse($activitiesData as $activity)
                        <tr>
                            <td>{{ ucfirst(str_replace('_', ' ', $activity->action ?? '-')) }}</td>
                            <td>{{ $activity->model_type ?? 'System' }}</td>
                            <td>{{ $activity->user?->name ?? 'System' }}</td>
                            <td>{{ $activity->description ?? '-' }}</td>
                            <td>{{ $activity->created_at ? $activity->created_at->format('H:i:s') : '-' }}</td>
                        </tr>
                    @empty
                        <tr><td colspan="5">No activities available.</td></tr>
                    @endforelse
                    @if($activitiesData->isNotEmpty())
                        <tr>
                            <th colspan="4">Total Activities</th>
                            <th class="text-right">{{ $activitiesTotal }}</th>
                        </tr>
                    @endif
                </tbody>
            </table>
        </div>
    @endif

    <div class="section">
        <h3>Overall Summary</h3>
        @php
            $salesSummaryTotal = $salesOrdersData->sum('total');
            $expensesSummaryTotal = $sections['includeExpenses'] ? $expensesData->flatMap(fn($items) => $items)->sum('amount') : 0;
            $purchasesSummaryTotal = $sections['includePurchases'] ? $purchasesData->sum('total_amount') : 0;
            $deliveriesSummaryTotal = $sections['includeDeliveries'] ? $deliveriesData->sum('cost') : 0;
            $summaryRows = collect([
                ['label' => 'Sales', 'value' => $salesSummaryTotal, 'display' => 'LKR ' . number_format($salesSummaryTotal, 2)],
                $sections['includeExpenses'] ? ['label' => 'Expenses', 'value' => $expensesSummaryTotal, 'display' => '- LKR ' . number_format($expensesSummaryTotal, 2)] : null,
                $sections['includePurchases'] ? ['label' => 'Purchases', 'value' => $purchasesSummaryTotal, 'display' => '- LKR ' . number_format($purchasesSummaryTotal, 2)] : null,
                $sections['includeDeliveries'] ? ['label' => 'Deliveries', 'value' => $deliveriesSummaryTotal, 'display' => '- LKR ' . number_format($deliveriesSummaryTotal, 2)] : null,
            ])->filter();
            $overallSummaryTotal = $salesSummaryTotal - $expensesSummaryTotal - $purchasesSummaryTotal - $deliveriesSummaryTotal;
        @endphp
        <table>
            <thead>
                <tr>
                    <th>Section</th>
                    <th class="text-right">Total Value</th>
                </tr>
            </thead>
            <tbody>
                @foreach($summaryRows as $row)
                    <tr>
                        <td>{{ $row['label'] }}</td>
                        <td class="text-right">{{ $row['display'] }}</td>
                    </tr>
                @endforeach
                <tr>
                    <th>Balance After Expenses, Purchases and Deliveries</th>
                    <th class="text-right">LKR {{ number_format($overallSummaryTotal, 2) }}</th>
                </tr>
            </tbody>
        </table>
    </div>
</body>
</html>
