<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Monthly Sales Report</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 11px; color: #1f2937; }
        .header { border-bottom: 2px solid #2563eb; padding-bottom: 10px; margin-bottom: 14px; }
        .title { font-size: 18px; font-weight: bold; margin-bottom: 4px; }
        .muted { color: #6b7280; }
        .section { margin-top: 14px; page-break-inside: avoid; }
        .section h3 { font-size: 13px; margin: 0 0 8px; color: #111827; }
        table { width: 100%; border-collapse: collapse; }
        th, td { border: 1px solid #e5e7eb; padding: 6px; vertical-align: top; }
        th { background: #f3f4f6; text-align: left; }
        .text-right { text-align: right; }
        .text-center { text-align: center; }
    </style>
</head>
<body>
    <div class="header">
        <div class="title">Monthly Sales Report</div>
        <div class="muted">Month: {{ $selectedMonth->format('F Y') }}</div>
        <div class="muted">Generated by: {{ $generatedBy }} | {{ $generatedAt->format('F d, Y h:i A') }}</div>

        @if($sections['includeHeader'])
            <div style="margin-top: 8px;">
                <strong>Company:</strong> {{ $shop->name ?? 'N/A' }}<br>
                <strong>Email:</strong> {{ $shop->email ?? 'N/A' }}<br>
                <strong>Address:</strong> {{ $shop->address ?? 'N/A' }}<br>
                <strong>Phone:</strong> {{ $shop->phone ?? 'N/A' }}
            </div>
        @endif
    </div>

    @if($sections['includeSummary'] && $salesData)
        <div class="section">
            <h3>Monthly Sales Summary</h3>
            <table>
                <tr><th>Total Sales</th><td class="text-right">LKR {{ number_format($salesData['total_sales'], 2) }}</td></tr>
                <tr><th>Total Orders</th><td class="text-right">{{ $salesData['total_orders'] }}</td></tr>
                <tr><th>Total Items Sold</th><td class="text-right">{{ $salesData['total_items_sold'] }}</td></tr>
                <tr><th>Gross Profit</th><td class="text-right">LKR {{ number_format($salesData['gross_profit'], 2) }}</td></tr>
                <tr><th>Average Order Value</th><td class="text-right">LKR {{ number_format($salesData['average_order_value'], 2) }}</td></tr>
            </table>
        </div>
    @endif

    @if($sections['includeTopDays'])
        <div class="section">
            <h3>Top Performing Days</h3>
            @php $topDays = $dailyData->sortByDesc('total_sales')->take(10); @endphp
            <table>
                <thead>
                    <tr>
                        <th>Date</th>
                        <th class="text-right">Orders</th>
                        <th class="text-right">Sales</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse($topDays as $day)
                        <tr>
                            <td>{{ \Carbon\Carbon::parse($day->date)->format('Y-m-d') }}</td>
                            <td class="text-right">{{ $day->order_count }}</td>
                            <td class="text-right">LKR {{ number_format($day->total_sales, 2) }}</td>
                        </tr>
                    @empty
                        <tr><td colspan="3">No daily records available.</td></tr>
                    @endforelse
                </tbody>
            </table>
        </div>
    @endif

    @if($sections['includeStatistics'])
        <div class="section">
            <h3>Monthly Statistics</h3>
            <table>
                <tr><th>Days in Month</th><td class="text-right">{{ $selectedMonth->daysInMonth }}</td></tr>
                <tr><th>Active Sales Days</th><td class="text-right">{{ safe_count($dailyData) }}</td></tr>
                <tr><th>Avg Daily Revenue</th><td class="text-right">LKR {{ number_format(($salesData['total_sales'] ?? 0) / max($selectedMonth->daysInMonth, 1), 2) }}</td></tr>
                <tr><th>Best Day Sales</th><td class="text-right">LKR {{ number_format($dailyData->max('total_sales') ?? 0, 2) }}</td></tr>
            </table>
        </div>
    @endif

    @if($sections['includeExpenses'])
        <div class="section">
            <h3>Monthly Expenses</h3>
            @php $expenseRows = $expensesData->flatMap(fn($items) => $items); @endphp
            <table>
                <thead>
                    <tr>
                        <th>Type</th>
                        <th>Description</th>
                        <th class="text-right">Amount</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse($expenseRows as $expense)
                        <tr>
                            <td>{{ ucfirst(str_replace('_', ' ', $expense->type ?? '')) }}</td>
                            <td>{{ $expense->notes ?? '-' }}</td>
                            <td class="text-right">LKR {{ number_format($expense->amount ?? 0, 2) }}</td>
                        </tr>
                    @empty
                        <tr><td colspan="3">No expenses available.</td></tr>
                    @endforelse
                    @if($expenseRows->isNotEmpty())
                        <tr>
                            <th colspan="2">Total Expenses</th>
                            <th class="text-right">LKR {{ number_format($expenseRows->sum('amount'), 2) }}</th>
                        </tr>
                    @endif
                </tbody>
            </table>
        </div>
    @endif

    @if($sections['includeTransactions'])
        <div class="section">
            <h3>Monthly Transactions</h3>
            <table>
                <thead>
                    <tr>
                        <th>Type</th>
                        <th>Vendor</th>
                        <th>Status</th>
                        <th class="text-right">Amount</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse($transactionsData as $transaction)
                        <tr>
                            <td>{{ ucfirst(str_replace('_', ' ', $transaction->transaction_type ?? '-')) }}</td>
                            <td>{{ $transaction->vendor_name ?? 'N/A' }}</td>
                            <td>{{ ucfirst($transaction->status ?? '-') }}</td>
                            <td class="text-right">LKR {{ number_format($transaction->total_amount ?? 0, 2) }}</td>
                        </tr>
                    @empty
                        <tr><td colspan="4">No transactions available.</td></tr>
                    @endforelse
                    @if($transactionsData->isNotEmpty())
                        <tr>
                            <th colspan="3">Total Transactions Value</th>
                            <th class="text-right">LKR {{ number_format($transactionsData->sum('total_amount'), 2) }}</th>
                        </tr>
                    @endif
                </tbody>
            </table>
        </div>
    @endif

    @if($sections['includeTransactionSummary'])
        <div class="section">
            <h3>Transactions Summary by Category</h3>
            <table>
                <thead>
                    <tr>
                        <th>Category</th>
                        <th class="text-right">Count</th>
                        <th class="text-right">Total</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse($transactionsSummary as $summary)
                        <tr>
                            <td>{{ ucfirst($summary->category ?? 'Uncategorized') }}</td>
                            <td class="text-right">{{ $summary->count }}</td>
                            <td class="text-right">LKR {{ number_format($summary->total, 2) }}</td>
                        </tr>
                    @empty
                        <tr><td colspan="3">No summary data available.</td></tr>
                    @endforelse
                    @if($transactionsSummary->isNotEmpty())
                        <tr>
                            <th>Total</th>
                            <th class="text-right">{{ $transactionsSummary->sum('count') }}</th>
                            <th class="text-right">LKR {{ number_format($transactionsSummary->sum('total'), 2) }}</th>
                        </tr>
                    @endif
                </tbody>
            </table>
        </div>
    @endif

    @if($sections['includeDeliveries'])
        <div class="section">
            <h3>Monthly Deliveries</h3>
            <table>
                <thead>
                    <tr>
                        <th>Tracking #</th>
                        <th>From</th>
                        <th>To</th>
                        <th class="text-right">Cost</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse($deliveriesData as $delivery)
                        <tr>
                            <td>{{ $delivery->tracking_number ?? 'N/A' }}</td>
                            <td>{{ $delivery->from_location ?? '-' }}</td>
                            <td>{{ $delivery->to_location ?? '-' }}</td>
                            <td class="text-right">LKR {{ number_format($delivery->cost ?? 0, 2) }}</td>
                        </tr>
                    @empty
                        <tr><td colspan="4">No deliveries available.</td></tr>
                    @endforelse
                    @if($deliveriesData->isNotEmpty())
                        <tr>
                            <th colspan="3">Total Delivery Cost</th>
                            <th class="text-right">LKR {{ number_format($deliveriesData->sum('cost'), 2) }}</th>
                        </tr>
                    @endif
                </tbody>
            </table>
        </div>
    @endif

    @if($sections['includeActivities'])
        <div class="section">
            <h3>Monthly Activity Log</h3>
            <table>
                <thead>
                    <tr>
                        <th>Action</th>
                        <th>Model</th>
                        <th>User</th>
                        <th>Description</th>
                        <th>Time</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse($activitiesData as $activity)
                        <tr>
                            <td>{{ ucfirst(str_replace('_', ' ', $activity->action ?? '-')) }}</td>
                            <td>{{ $activity->model_type ?? 'System' }}</td>
                            <td>{{ $activity->user?->name ?? 'System' }}</td>
                            <td>{{ $activity->description ?? '-' }}</td>
                            <td>{{ $activity->created_at ? $activity->created_at->format('Y-m-d H:i') : '-' }}</td>
                        </tr>
                    @empty
                        <tr><td colspan="5">No activities available.</td></tr>
                    @endforelse
                    @if($activitiesData->isNotEmpty())
                        <tr>
                            <th colspan="4">Total Activities</th>
                            <th class="text-right">{{ $activitiesData->count() }}</th>
                        </tr>
                    @endif
                </tbody>
            </table>
        </div>
    @endif
</body>
</html>
